name: Avalonia Crossplatform Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore JDKSwitcher/JDKSwitcher.csproj
      - name: Build
        run: dotnet build JDKSwitcher/JDKSwitcher.csproj --configuration Release --no-restore
      - name: Publish Linux x64
        run: dotnet publish JDKSwitcher/JDKSwitcher.csproj -c Release -r linux-x64 --self-contained true -o publish-linux
      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: JDKSwitcher-linux-x64
          path: publish-linux/

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore JDKSwitcher/JDKSwitcher.csproj
      - name: Build
        run: dotnet build JDKSwitcher/JDKSwitcher.csproj --configuration Release --no-restore
      - name: Publish Windows x64
        run: dotnet publish JDKSwitcher/JDKSwitcher.csproj -c Release -r win-x64 --self-contained true -o publish-win
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: JDKSwitcher-win-x64
          path: publish-win/
